# Матрица `M`

Сначала создаём матрицу $ M $ размером $ 85 \times 85 $, используя функцию `np.full()`. Все элементы этой матрицы инициализируются значением 2.

Затем с помощью функции `np.fill_diagonal()` заполняем главную диагональ матрицы значениями, вычисляемыми по формуле $ 2i + 1 $, где $ i $ — индекс элемента на диагонали, начиная с 1. Это значит, что элементы на диагонали будут следующими:
- Для $ i = 1 $ — $ 2 \times 1 + 1 = 3 $,
- Для $ i = 2 $ — $ 2 \times 2 + 1 = 5 $,
- Для $ i = 3 $ — $ 2 \times 3 + 1 = 7 $,
- И так далее.

Таким образом, на диагонали будут стоять нечётные числа, начиная с 3, и увеличиваться на 2, а все остальные элементы матрицы будут равны 2.

Функция `np.arange()` создаёт одномерный массив с равномерно распределёнными элементами в заданном диапазоне.

### Синтаксис:
```python
np.arange([start, ] stop, [step, ]) dtype=None
```

- **start** — начальное значение (по умолчанию 0).
- **stop** — конечное значение (не включается в массив).
- **step** — шаг (по умолчанию 1).
- **dtype** — тип данных элементов (по умолчанию `None`).

Пример:
```python
np.arange(0, 10, 2)  # Возвращает: [0, 2, 4, 6, 8]
```

Функция не включает значение `stop` в массив. Работает с целыми и дробными шагами.

In [ ]:
import numpy as np

size = 85

M = np.full((size, size), 2)

np.fill_diagonal(M, 2 * np.arange(1, size + 1) + 1)

print(M)


[[  3   2   2 ...   2   2   2]
 [  2   5   2 ...   2   2   2]
 [  2   2   7 ...   2   2   2]
 ...
 [  2   2   2 ... 167   2   2]
 [  2   2   2 ...   2 169   2]
 [  2   2   2 ...   2   2 171]]


# Матрица `N`

1. Матрица $ N $ создается с помощью `np.full()`, где все элементы по умолчанию равны 4.
2. Для нечётных строк каждое 3-е число заменяется на 5 с использованием срезов `N[::2, 2::3]`. Это означает:
   - `::2` — выбираются все нечётные строки.
   - `2::3` — начиная с третьего элемента (индекса 2), каждый третий элемент заменяется на 5.
3. Для чётных строк каждое 2-е число заменяется на 7 с помощью срезов `N[1::2, 1::2]`. Это означает:
   - `1::2` — выбираются все чётные строки.
   - `1::2` — начиная с второго элемента (индекса 1), каждый второй элемент заменяется на 7.

Когда используются срезы с двумя двоеточиями, например `::`, это означает, что используется **только шаг**, и срез захватывает весь массив (или строку/столбец), начиная с первого элемента.

### Примеры использования `::` в срезах:

1. **`::2`** — это срез, который выбирает каждый второй элемент массива (начиная с первого):
   - Если применяется к строкам или столбцам, это вернёт все элементы с чётными индексами (0, 2, 4, ...).

2. **`1::2`** — это срез, который выбирает все элементы массива, начиная с индекса 1, с шагом 2:
   - Это будет выбирать все элементы с нечётными индексами (1, 3, 5, ...).

3. **`::3`** — это срез, который выбирает каждый третий элемент массива:
   - Например, это вернёт элементы с индексами 0, 3, 6, 9, и так далее.

4. **`i::`** — срез, который начинает выборку с индекса `i` и продолжает до конца массива.

In [ ]:
import numpy as np

size = 85

N = np.full((size, size), 4)

N[::2, 2::3] = 5

N[1::2, 1::2] = 7

print(N)


[[4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]
 ...
 [4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]]


# Вектор `p`

1. **Размер вектора**:
   Вектор $ p $ состоит из 85 элементов. Это связано с формулой $ \{1 + p_i : p_i \sim N(2, 4)\}_{i=0}^{84} $, где индексы $ i $ варьируются от 0 до 84 включительно. Таким образом, размер вектора $ size = 85 $.

   В коде размер задаётся параметром `size` в функции `np.random.normal()`:
   ```python
   np.random.normal(mean, std_dev, size)
   ```
   Здесь `size=85` указывает на то, что функция должна сгенерировать массив длиной 85.

2. **Работа функции `np.random.normal`**:
   - Функция `np.random.normal(mean, std_dev, size)` генерирует массив случайных чисел из нормального распределения с заданным математическим ожиданием (`mean`) и стандартным отклонением (`std_dev`).
   - **Аргументы функции**:
     - `mean` — математическое ожидание, центр распределения. В данном случае оно равно $ 2 $.
     - `std_dev` — стандартное отклонение, которое определяет разброс значений вокруг среднего. Поскольку дисперсия $ \sigma^2 = 4 $, стандартное отклонение $ \sigma = \sqrt{4} = 2 $.
     - `size` — количество элементов в массиве, задающее длину вектора. Здесь оно равно 85.

3. **Добавление единицы**:
   После генерации массива случайных чисел функция добавляет 1 ко всем элементам с помощью выражения `1 + np.random.normal(...)`. Это смещает все значения массива на единицу вправо относительно исходного нормального распределения.

4. **Результат**:
   Итоговый вектор $ p $ состоит из 85 элементов, каждый из которых соответствует формуле $ 1 + p_i $, где $ p_i \sim N(2, 4) $.

In [ ]:
import numpy as np

size = 85
mean = 2
std_dev = 2

p = 1 + np.random.normal(mean, std_dev, size)

print(p)


[ 2.76139844  1.25060635  6.49299611  3.86917491  2.13109366  5.50271013
  4.22407191  3.13851613 -0.19075453  6.75854711  2.81872658  0.99028548
  4.67445751  1.23916574  5.12153057  2.92092321  6.71492608  2.59455124
  1.733897    3.94296701  4.75295546  2.17240073 -0.98876876  1.61412266
  0.90893836  2.43498341  4.88028695 -1.09961164  3.77425553  3.49217415
  4.78622599  6.89487207  6.53419428  2.841143    3.69670004  3.69766289
  3.85939513  3.65090749  5.00683518  2.34475059  4.8435791   3.91353965
  0.04138811  4.85315948  1.11003577  3.24743008  1.437725    5.35038393
  2.66852479  3.77801866  2.52325478  1.37872056  4.78330959  2.63145724
  5.78416026  7.58834203  2.18024645  2.05553877 -1.45764577  3.75679552
  1.0636216   4.86637556  1.89263967  4.07679695  1.43177826  6.03820545
  1.71470857  1.95621086  2.38171948  1.69763379  2.31272924  1.97695768
  2.23213311  6.0126461   2.13416883 -0.07060742  0.70395781  4.2287792
 -0.65424311  1.56887184  0.67762495  0.7444797   3.

# Вектор $q^T$

### Объяснение создания вектора $ q^T $

1. **Формула**:
   Вектор $ q^T $ определяется как:
   $$
   q^T = \{ N_{24, j} \cdot N_{71, j} \}_{j=0}^{84}
   $$
   Это означает, что каждый элемент $ q^T_j $ получается путём поэлементного умножения элементов 24-й и 71-й строк матрицы $ N $ по всем $ j $ (столбцам матрицы).

2. **Извлечение строк**:
   - Для получения 24-й строки (с индексом 23, так как индексация в Python начинается с 0) используется:
     ```python
     N[23, :]
     ```
   - Для получения 71-й строки (с индексом 70):
     ```python
     N[70, :]
     ```

3. **Поэлементное умножение**:
   - Оператор `*` в NumPy выполняет поэлементное умножение массивов одинаковой длины.
   - В данном случае:
     ```python
     q_T = N[23, :] * N[70, :]
     ```
   - Это соответствует формуле:
     $$
     q^T_j = N_{24, j} \cdot N_{71, j}.
     $$

4. **Итоговый результат**:
   Вектор $ q^T $ имеет длину 85, так как каждая строка матрицы $ N $ содержит 85 элементов. Каждый элемент вектора — результат умножения соответствующих элементов из строк 24 и 71.

In [ ]:
row_24 = N[23, :]
row_71 = N[70, :]

q_T = row_24 * row_71

print(q_T)


[16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35
 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35
 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35
 16 28 20 28 16 35 16 28 20 28 16 35 16]


# Индивидуальное задание 4

1. **Поэлементное произведение $ N p $**:
   Для каждого элемента матрицы $ N $ и вектора $ p $ нужно выполнить поэлементное умножение. То есть для каждого элемента $ (N p)_i $ мы умножаем значение в матрице $ N $ на соответствующий элемент вектора $ p $.

   В Python это можно сделать с помощью поэлементного умножения:
   ```python
   N_p = N * p
   ```

   Этот код создаёт новую матрицу $ N_p $, где каждый элемент $ (N p)_i $ является произведением соответствующего элемента матрицы $ N $ на элемент вектора $ p $.

2. **Исключение элемента с индексом 37**:
   Далее мы должны исключить из суммирования элемент с индексом 37. Для этого можно использовать индексацию в numpy, чтобы вычесть значение, которое соответствует индексу 37.

   Сначала мы суммируем все элементы вектора $ N_p $ по строкам (или столбцам, в зависимости от контекста), а затем вычитаем элемент с индексом 37:
   ```python
   sum_N_p_exclude_37 = np.sum(N_p, axis=0) - N_p[37]
   ```

   Здесь:
   - `np.sum(N_p, axis=0)` выполняет суммирование всех элементов матрицы $ N_p $ по строкам.
   - `N_p[37]` — это значение, соответствующее элементу с индексом 37, которое мы вычитаем из суммы.

3. **Умножение на вектор $ q $**:
   После вычисления суммы, исключив элемент с индексом 37, результат умножается на вектор $ q $. Это делается с помощью скалярного произведения вектора $ q $ и результата суммы.

   В Python для этого используется функция `np.dot()`:
   ```python
   f4 = np.dot(q, sum_N_p_exclude_37)
   ```

   Функция `np.dot()` вычисляет скалярное произведение вектора $ q $ и суммы элементов $ (N p)_i $ (за исключением индекса 37).

In [ ]:
# Поэлементное произведение N и p
N_p = N * p

# Суммирование элементов, исключая i = 37
sum_N_p_exclude_37 = np.sum(N_p, axis=0) - N_p[37]

# Умножение на вектор q
f4 = np.dot(q_T.T, sum_N_p_exclude_37)

print(f4)


2724151.5296598654


1. **Поэлементное произведение $ p \odot q $**:
   Для вычисления поэлементного произведения векторов $ p $ и $ q $, используется стандартное поэлементное умножение в Python:
   ```python
   p_q = p * q
   ```
   Этот шаг создаёт новый вектор, где каждый элемент $ (p \odot q)_i $ является произведением соответствующих элементов из векторов $ p $ и $ q $.

2. **Создание маски для исключения элементов, где $ i = M_{ii} $**:
   Следующим шагом необходимо создать маску для индексов $ i $, которые не равны диагональным элементам матрицы $ M $. Для этого извлекаем диагональные элементы матрицы $ M $ с помощью функции `np.diagonal(M)` и сравниваем их с диапазоном индексов от 12 до 76:
   ```python
   mask = np.diagonal(M) != np.arange(12, 77)
   ```
   Здесь:
   - `np.diagonal(M)` извлекает диагональные элементы матрицы $ M $.
   - `np.arange(12, 77)` генерирует массив индексов от 12 до 76.
   - Операция `!=` создаёт булеву маску, где каждый элемент будет равен True (1), если индекс $ i $ не равен соответствующему элементу на диагонали матрицы $ M $.

3. **Суммирование элементов с исключением $ i = M_{ii} $**:
   После того как мы создали маску, можем суммировать элементы поэлементного произведения $ p \odot q $, применяя маску для исключения тех элементов, где $ i = M_{ii} $. Для этого используем:
   ```python
   g4 = np.sum(p_q[12:77] * mask)
   ```
   В этой строке:
   - `p_q[12:77]` извлекает элементы вектора $ p \odot q $ в диапазоне от 12 до 76.
   - `mask` применяется к этим элементам, исключая те, где $ i = M_{ii} $.

In [ ]:
# Поэлементное произведение p и q
p_q = p * q

# Проверка, что i не равняется Mii
mask = np.diagonal(M) != np.arange(12, 77)

# Суммирование элементов с учетом маски
g4 = np.sum(p_q[12:77] * mask)

print(g4)
